[project]
name = "repo-health-checker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.2.3",
    "prettytable>=3.12.0",
    "requests>=2.32.3",
]
